"""Reconcile paper counts between PAPER_SUMMARIES.md, PAPER_INDEX.md, and papers/.

Definitions:
- A "paper entry" is one ``###`` block in PAPER_SUMMARIES.md; a "section" is
  one ``##`` header.
- An entry is "local" if a ``- **File:**`` bullet resolves to a PDF: a ref is
  tried under ``papers/``, then under each ``extra_pdf_dirs`` root from the
  config, then relative to the repo root.
- An entry is "text-only" if it has no local PDF but a text-extraction ref
  (``.txt``/``.md``) resolves.
- An entry is "reference-only" if its block says so (case-insensitive).
- Anything else is "unclassified" and needs remediation.
- The unreferenced sweep covers ``papers/`` only, minus ``exempt_dirs`` from
  the config (PDFs catalogued by some other index). Extra PDF dirs are
  curated: their contents resolve when referenced but need no entries.
- Every top-level ``papers/*.pdf`` must have a ``papers/text/<stem>.txt``
  (or ``.md``) extraction.
- The ``pending_index`` file lists PDFs awaiting summaries; they don't fail
  the check but are surfaced, and stale lines are failures.

Config — ``paper_index.toml`` at the repo root; the file and every key are
optional::

    [paths]
    extra_pdf_dirs = ["blogs", "gladstone"]     # default []
    exempt_dirs = ["papers/org_docs"]           # default []
    pending_index = "papers/pending_index.txt"  # default as shown

Parsed with ``tomllib`` on Python 3.11+; older interpreters (a stock macOS
``python3`` is 3.9) get a parser for exactly that subset — one table, string
and string-array values, ``#`` comments. Runs on 3.9+.

Doc claims checked:
- PAPER_SUMMARIES.md header: "> N papers total" == local + text-only.
- PAPER_INDEX.md: "Summaries of N papers across M sections" == entries/sections;
  "N papers have local PDFs" == local; "N are reference-only" == ref-only.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

try:
    import tomllib
except ImportError:  # Python < 3.11
    tomllib = None

CONFIG_FILE = "paper_index.toml"
DEFAULT_PENDING_INDEX = "papers/pending_index.txt"
CONFIG_KEYS = ("extra_pdf_dirs", "exempt_dirs", "pending_index")

# Value is either backticked (trailing annotations allowed: "`X.pdf` (10 pp)")
# or a bare single token; prose values like "Not available locally (...)" fall
# through both and are ignored.
FILE_BULLET_RE = re.compile(r"^- \*\*File:?\*\*:?\s*(?:`([^`]+)`.*|(\S+))\s*$")
TEXT_BULLET_RE = re.compile(
    r"^- \*\*Text(?: extraction)?:?\*\*:?\s*(?:`([^`]+)`.*|(\S+))\s*$"
)
# Multi-part reports: "- **Files:**" followed by indented sub-bullets.
FILES_HEADER_RE = re.compile(r"^- \*\*Files:?\*\*:?\s*$")
SUB_BULLET_RE = re.compile(r"^\s+- (?:`([^`]+)`.*|(\S+))\s*$")
REFERENCE_ONLY_RE = re.compile(r"reference-only", re.IGNORECASE)
# Condense fields (contract shared with the condense-summary skill's
# condense_check.py — keep these regexes identical to its).
TITLE_RE = re.compile(r"^\*\*Title:\*\*\s*(.+?)\s*$")
FOCUS_RE = re.compile(r"^- \*\*Focus:\*\*\s*(.+?)\s*$")
ONE_LINER_RE = re.compile(r"^- \*\*One-liner:\*\*\s*(.+?)\s*$")
INDEX_LABEL_RE = re.compile(r"^- \*\*Index label:\*\*\s*(.+?)\s*$")
# ``Related`` is canonical; the others are legacy spellings still in the file.
RELATED_NAMES = (
    "Related",
    "Relationship to other repo entries",
    "Cross-references (in this collection)",
    "Cross-references in this collection",
    "Cross-references",
    "Companions in this collection",
)
RELATED_RE = re.compile(
    r"^- \*\*("
    + "|".join(re.escape(n) for n in RELATED_NAMES)
    + r"):?\*\*:?\s*(.*?)\s*$"
)
BACKTICK_SLUG_RE = re.compile(r"`([a-z0-9][a-z0-9-]*)`")

SUMMARIES_TOTAL_RE = re.compile(
    r"^> (\d+) papers total \((\d+) with local PDFs, (\d+) text-only\)",
    re.MULTILINE,
)
INDEX_ENTRIES_RE = re.compile(r"Summaries of (\d+) papers across (\d+) sections")
INDEX_LOCAL_RE = re.compile(r"(\d+) papers have local PDFs")
INDEX_REF_RE = re.compile(r"(\d+) are reference-only")
# The **papers/** bullet is the entry point for browse-by-topic. If it's
# missing entirely, the section-list check has nothing to verify — so the
# absence itself is the failure.
INDEX_PAPERS_BULLET_RE = re.compile(r"^\*\*papers/\*\*\s*—", re.MULTILINE)
# Nested rows under **papers/** — one per PAPER_SUMMARIES ## section.
# Captures three groups: display name, anchor slug, count. Every one is
# checked in _check_section_list.
INDEX_SECTION_ROW_RE = re.compile(
    r"^  - \[([^\]]+)\]\(PAPER_SUMMARIES\.md#([^)]+)\) \((\d+)\)\s*$",
    re.MULTILINE,
)


def _github_slug(text: str) -> str:
    """Approximate GitHub's autogenerated anchor for a markdown header.

    GitHub's rule, verified empirically 2026-09-05 against a Gist render:
    lowercase, drop chars that aren't ``\\w`` / whitespace / hyphen,
    strip, replace each ``0x20`` space with one hyphen (runs are NOT
    collapsed -- ``"Foo  Bar"`` renders as ``#foo--bar``), and drop
    non-space whitespace entirely (``"Foo\\tBar"`` renders as
    ``#foobar``, not ``#foo-bar``).

    This subset matches every ``## `` header currently in
    ``PAPER_SUMMARIES.md`` (Latin letters, ASCII punctuation, single
    spaces only). If a future header uses characters GitHub handles
    specially (e.g., ``&`` → ``and``), extend the rule and add a
    targeted regression test.
    """
    s = text.lower()
    s = re.sub(r"[^\w\s-]", "", s).strip()
    # Non-space whitespace (tab, CR, LF, FF, VT) is dropped by GitHub; only
    # the literal space char becomes a hyphen, and one hyphen per space.
    s = re.sub(r"[^\S ]", "", s)
    return s.replace(" ", "-")


@dataclass
class Entry:
    slug: str  # the ``### `` heading text
    line: int
    section: str = ""
    title: str = ""  # the ``**Title:**`` line
    pdf_refs: list[str] = field(default_factory=list)
    text_refs: list[str] = field(default_factory=list)
    body: str = ""
    category: str = "unclassified"
    focus: str | None = None
    one_liner: str | None = None
    index_label: str | None = None
    related: list[str] = field(default_factory=list)
    related_field_name: str | None = None


@dataclass
class Config:
    extra_pdf_dirs: list[str] = field(default_factory=list)
    exempt_dirs: list[str] = field(default_factory=list)
    pending_index: str = DEFAULT_PENDING_INDEX


class ConfigError(ValueError):
    """paper_index.toml is unreadable or names something unknown."""


_TOML_STRING_RE = re.compile(r'"([^"\\]*)"')
_TOML_KEY_RE = re.compile(r"([A-Za-z0-9_-]+)\s*=\s*(.+)")


def _strip_toml_comment(line: str) -> str:
    out: list[str] = []
    in_string = False
    for ch in line:
        if ch == '"':
            in_string = not in_string
        elif ch == "#" and not in_string:
            break
        out.append(ch)
    return "".join(out)


def _parse_toml_value(val: str, lineno: int) -> str | list[str]:
    if m := _TOML_STRING_RE.fullmatch(val):
        return m.group(1)
    if val.startswith("[") and val.endswith("]"):
        inner = val[1:-1].strip()
        if not inner:
            return []
        items = [s.strip() for s in inner.split(",")]
        if items[-1] == "":  # trailing comma
            items.pop()
        out: list[str] = []
        for item in items:
            m = _TOML_STRING_RE.fullmatch(item)
            if not m:
                raise ValueError(f"line {lineno}: array items must be quoted strings")
            out.append(m.group(1))
        return out
    raise ValueError(
        f"line {lineno}: unsupported value {val!r} (quoted strings and string arrays only)"
    )


def parse_toml_subset(text: str) -> dict:
    """The TOML subset ``paper_index.toml`` uses, for interpreters without
    ``tomllib``: ``[table]`` headers, ``key = "string"``, ``key = ["a", "b"]``,
    ``#`` comments. Agrees with ``tomllib.loads`` on that subset; anything
    outside it raises ``ValueError``."""
    data: dict = {}
    table = data
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = _strip_toml_comment(raw).strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            name = line[1:-1].strip()
            if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
                raise ValueError(f"line {lineno}: bad table header {raw.strip()!r}")
            table = data.setdefault(name, {})
            continue
        m = _TOML_KEY_RE.fullmatch(line)
        if not m:
            raise ValueError(f"line {lineno}: cannot parse {raw.strip()!r}")
        table[m.group(1)] = _parse_toml_value(m.group(2).strip(), lineno)
    return data


def load_config(root: Path) -> Config:
    """Read ``paper_index.toml`` from the repo root; defaults when absent.
    Raises ``ConfigError`` (named, no traceback at the CLI) on bad input."""
    path = root / CONFIG_FILE
    if not path.is_file():
        return Config()
    text = path.read_text(encoding="utf-8")
    try:
        data = tomllib.loads(text) if tomllib else parse_toml_subset(text)
    except ValueError as exc:  # tomllib.TOMLDecodeError is a ValueError
        raise ConfigError(f"{CONFIG_FILE}: {exc}") from exc
    paths = data.get("paths", {})
    unknown = sorted(set(paths) - set(CONFIG_KEYS))
    if unknown:
        raise ConfigError(
            f"{CONFIG_FILE}: unknown key(s) under [paths]: {', '.join(unknown)} "
            f"(known: {', '.join(CONFIG_KEYS)})"
        )
    for key in ("extra_pdf_dirs", "exempt_dirs"):
        val = paths.get(key, [])
        if not isinstance(val, list) or not all(isinstance(d, str) for d in val):
            raise ConfigError(f"{CONFIG_FILE}: {key} must be a list of strings")
    pending = paths.get("pending_index", DEFAULT_PENDING_INDEX)
    if not isinstance(pending, str):
        raise ConfigError(f"{CONFIG_FILE}: pending_index must be a string")
    return Config(
        extra_pdf_dirs=list(paths.get("extra_pdf_dirs", [])),
        exempt_dirs=list(paths.get("exempt_dirs", [])),
        pending_index=pending,
    )


@dataclass
class Report:
    counts: dict
    problems: dict
    info: dict = field(default_factory=dict)
    entries: list[Entry] = field(default_factory=list)
    sections: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(self.problems.values())


def parse_entries(md_text: str) -> tuple[list[Entry], list[str]]:
    """Return (entries, ordered section names) from PAPER_SUMMARIES.md text.

    Section names are the authority for the section-list check — a ``##``
    header with zero ``###`` entries still needs a row in PAPER_INDEX.md,
    so building the list from headers (not from entries) matters.
    """
    lines = md_text.splitlines()
    sections: list[str] = []
    entries: list[Entry] = []
    current: Entry | None = None
    current_section: str = ""
    body_lines: list[str] = []
    in_files_list = False

    def flush():
        if current is not None:
            current.body = "\n".join(body_lines)

    for i, line in enumerate(lines, start=1):
        if line.startswith("### "):
            flush()
            current = Entry(slug=line[4:].strip(), line=i, section=current_section)
            entries.append(current)
            body_lines = []
            in_files_list = False
        elif line.startswith("## "):
            flush()
            current = None
            current_section = line[3:].strip()
            sections.append(current_section)
            body_lines = []
            in_files_list = False
        elif current is not None:
            body_lines.append(line)
            if in_files_list:
                if m := SUB_BULLET_RE.match(line):
                    val = (m.group(1) or m.group(2)).strip()
                    if val.endswith(".pdf"):
                        current.pdf_refs.append(val)
                    elif val.endswith((".txt", ".md")):
                        current.text_refs.append(val)
                    continue
                in_files_list = False
            if FILES_HEADER_RE.match(line):
                in_files_list = True
            elif m := FILE_BULLET_RE.match(line):
                val = (m.group(1) or m.group(2)).strip()
                if val.endswith(".pdf"):
                    current.pdf_refs.append(val)
                elif val.endswith((".txt", ".md")):
                    current.text_refs.append(val)
                # Non-path values ("Not available locally") are ignored.
            elif m := TEXT_BULLET_RE.match(line):
                val = (m.group(1) or m.group(2)).strip()
                if val.endswith((".txt", ".md")):
                    current.text_refs.append(val)
            elif m := TITLE_RE.match(line):
                current.title = m.group(1)
            elif m := FOCUS_RE.match(line):
                current.focus = m.group(1)
            elif m := ONE_LINER_RE.match(line):
                current.one_liner = m.group(1)
            elif m := INDEX_LABEL_RE.match(line):
                current.index_label = m.group(1)
            elif m := RELATED_RE.match(line):
                current.related_field_name = m.group(1)
                current.related = BACKTICK_SLUG_RE.findall(m.group(2))
    flush()
    return entries, sections


def section_counts(entries: list[Entry], sections: list[str]) -> dict[str, int]:
    """Entries per ``##`` section, in section order; zero-entry sections kept.

    Entries whose section is empty (orphans before the first ``##``) are
    excluded so no fake section name is fabricated.
    """
    actual: dict[str, int] = {name: 0 for name in sections}
    for e in entries:
        if e.section in actual:
            actual[e.section] += 1
    return actual


def _resolve(root: Path, ref: str, extra_dirs: list[str] = ()) -> Path | None:
    """Resolve a File/Text bullet value: papers/, each extra dir, the root."""
    candidates = [root / "papers" / ref]
    candidates += [root / d / ref for d in extra_dirs]
    candidates.append(root / ref)
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def audit_repo(root: Path | str) -> Report:
    root = Path(root)
    cfg = load_config(root)
    md_text = (root / "PAPER_SUMMARIES.md").read_text(encoding="utf-8")
    entries, sections = parse_entries(md_text)

    papers_dir = root / "papers"
    all_pdfs = {p.relative_to(root).as_posix(): p for p in papers_dir.rglob("*.pdf")}

    broken_file_refs: list[str] = []
    broken_text_refs: list[str] = []
    resolved_refs: Counter[str] = Counter()  # root-relative path -> ref count
    ref_by_entry: dict[str, list[str]] = {}

    for e in entries:
        has_pdf = False
        for ref in e.pdf_refs:
            p = _resolve(root, ref, cfg.extra_pdf_dirs)
            if p is None:
                broken_file_refs.append(f"{e.slug}: {ref}")
            else:
                rel = p.relative_to(root).as_posix()
                resolved_refs[rel] += 1
                ref_by_entry.setdefault(rel, []).append(e.slug)
                has_pdf = True
        has_text = False
        for ref in e.text_refs:
            if _resolve(root, ref, cfg.extra_pdf_dirs) is None:
                broken_text_refs.append(f"{e.slug}: {ref}")
            else:
                has_text = True
        if has_pdf:
            e.category = "local_pdf"
        elif has_text:
            e.category = "text_only"
        elif REFERENCE_ONLY_RE.search(e.slug) or REFERENCE_ONLY_RE.search(e.body):
            e.category = "reference_only"
        else:
            e.category = "unclassified"

    counts = {
        "entries": len(entries),
        "sections": len(sections),
        "local_pdf": sum(e.category == "local_pdf" for e in entries),
        "text_only": sum(e.category == "text_only" for e in entries),
        "reference_only": sum(e.category == "reference_only" for e in entries),
        "unclassified": sum(e.category == "unclassified" for e in entries),
    }

    # The pending file (config `pending_index`): known-unreferenced PDFs
    # awaiting summaries. Valid entries don't fail the check but are surfaced
    # as info. Rotten lines (file gone, or summary already landed) ARE
    # failures — otherwise the allowlist accumulates dead weight invisibly.
    pending_path = root / cfg.pending_index
    pending: set[str] = set()
    if pending_path.is_file():
        pending = {
            stripped
            for line in pending_path.read_text(encoding="utf-8").splitlines()
            if (stripped := line.strip()) and not stripped.startswith("#")
        }
    pending_index_issues = sorted(
        f"listed but no such file on disk: {rel}" for rel in pending - set(all_pdfs)
    ) + sorted(
        f"summary already landed — remove from pending_index.txt: {rel}"
        for rel in pending & set(resolved_refs)
    )

    exempt_prefixes = tuple(d.rstrip("/") + "/" for d in cfg.exempt_dirs)
    unreferenced_pdfs = sorted(
        rel
        for rel in all_pdfs
        if rel not in resolved_refs
        and rel not in pending
        and not rel.startswith(exempt_prefixes)
    )
    pending_pdfs = sorted(rel for rel in all_pdfs if rel in pending)
    duplicate_file_refs = [
        f"{rel} referenced by {len(titles)} entries: {'; '.join(titles)}"
        for rel, titles in sorted(ref_by_entry.items())
        if len(titles) > 1
    ]
    text_dir = papers_dir / "text"
    pdfs_missing_text = sorted(
        p.name
        for p in papers_dir.glob("*.pdf")
        if not (text_dir / f"{p.stem}.txt").is_file()
        and not (text_dir / f"{p.stem}.md").is_file()
    )

    problems = {
        "unclassified_entries": [
            f"{e.slug} (line {e.line})" for e in entries if e.category == "unclassified"
        ],
        "orphan_entries_before_first_section": [
            f"{e.slug} (line {e.line})" for e in entries if e.section == ""
        ],
        "broken_file_refs": broken_file_refs,
        "broken_text_refs": broken_text_refs,
        "unreferenced_pdfs": unreferenced_pdfs,
        "duplicate_file_refs": duplicate_file_refs,
        "pdfs_missing_text": pdfs_missing_text,
        "pending_index_issues": pending_index_issues,
        "doc_claim_mismatches": _check_doc_claims(
            root, md_text, counts, entries, sections
        ),
    }
    info = {"pending_pdfs": pending_pdfs}
    return Report(
        counts=counts, problems=problems, info=info, entries=entries, sections=sections
    )


def _check_doc_claims(
    root: Path,
    md_text: str,
    counts: dict,
    entries: list[Entry],
    sections: list[str],
) -> list[str]:
    """Verify every claimed number. An absent pattern is a FAILURE, not a skip —
    a reworded doc that silently stops being checked is exactly the drift this
    tool exists to prevent."""
    mismatches: list[str] = []

    def compare(source: str, what: str, claimed: int, actual: int):
        if claimed != actual:
            mismatches.append(f"{source} claims {claimed} {what}, actual {actual}")

    def missing(source: str, pattern_desc: str):
        mismatches.append(
            f"{source}: claim pattern not found ({pattern_desc}) — "
            "doc reworded or pattern drift; fix the doc or the regex"
        )

    if m := SUMMARIES_TOTAL_RE.search(md_text):
        compare(
            "PAPER_SUMMARIES.md header",
            "local papers (local + text-only)",
            int(m.group(1)),
            counts["local_pdf"] + counts["text_only"],
        )
        compare(
            "PAPER_SUMMARIES.md header",
            "papers with local PDFs",
            int(m.group(2)),
            counts["local_pdf"],
        )
        compare(
            "PAPER_SUMMARIES.md header",
            "text-only papers",
            int(m.group(3)),
            counts["text_only"],
        )
    else:
        missing(
            "PAPER_SUMMARIES.md",
            "'> N papers total (N with local PDFs, N text-only)'",
        )

    index_path = root / "PAPER_INDEX.md"
    if not index_path.is_file():
        missing("PAPER_INDEX.md", "file does not exist")
        return mismatches
    index_text = index_path.read_text(encoding="utf-8")
    if m := INDEX_ENTRIES_RE.search(index_text):
        compare("PAPER_INDEX.md", "paper entries", int(m.group(1)), counts["entries"])
        compare("PAPER_INDEX.md", "sections", int(m.group(2)), counts["sections"])
    else:
        missing("PAPER_INDEX.md", "'Summaries of N papers across N sections'")
    if m := INDEX_LOCAL_RE.search(index_text):
        compare(
            "PAPER_INDEX.md",
            "papers with local PDFs",
            int(m.group(1)),
            counts["local_pdf"],
        )
    else:
        missing("PAPER_INDEX.md", "'N papers have local PDFs'")
    if m := INDEX_REF_RE.search(index_text):
        compare(
            "PAPER_INDEX.md",
            "reference-only papers",
            int(m.group(1)),
            counts["reference_only"],
        )
    else:
        missing("PAPER_INDEX.md", "'N are reference-only'")
    mismatches.extend(_check_section_list(index_text, entries, sections))
    return mismatches


def _check_section_list(
    index_text: str, entries: list[Entry], sections: list[str]
) -> list[str]:
    """Verify the **papers/** bullet's nested section list against reality.

    A browse-by-topic surface stays useful only if it stays honest. Four
    invariants:

    - The **papers/** bullet exists at all (browse-by-topic entry point).
    - Every ``## `` section in PAPER_SUMMARIES.md — including a header
      with zero ``###`` entries yet — appears exactly once as a nested
      ``- [Section](PAPER_SUMMARIES.md#slug) (N)`` row.
    - Every claimed ``N`` equals the actual count of ``### `` entries in
      that section.
    - Every row's ``#slug`` matches GitHub's autogenerated anchor for the
      section header (otherwise the link 404s on GitHub, defeating the
      whole point of a browse-by-topic surface).
    """
    problems: list[str] = []

    if not INDEX_PAPERS_BULLET_RE.search(index_text):
        problems.append(
            "PAPER_INDEX.md: **papers/** bullet not found — the browse-by-topic "
            "entry point is missing (expected '**papers/** — ...')"
        )
        return problems

    row_matches = INDEX_SECTION_ROW_RE.findall(index_text)
    if not row_matches:
        problems.append(
            "PAPER_INDEX.md: **papers/** bullet has no section list rows — "
            "expected nested '  - [Section Name](PAPER_SUMMARIES.md#slug) (N)' "
            "rows enumerating every ## section"
        )
        return problems

    # Actual per-section counts, keyed by ## header name in the order they
    # appear in PAPER_SUMMARIES.md. A section with zero entries yet is still
    # tracked — it needs a `(0)` row so the top-of-file "N sections" claim
    # and the per-section list stay consistent with each other.
    actual = section_counts(entries, sections)

    # Claimed rows: name -> (anchor, count). Duplicates are reported once
    # per repeated name (not N-1 times for N copies).
    claimed: dict[str, tuple[str, int]] = {}
    seen_dup: set[str] = set()
    for name, anchor, n_str in row_matches:
        if name in claimed and name not in seen_dup:
            problems.append(
                f"PAPER_INDEX.md section list has duplicate row for '{name}'"
            )
            seen_dup.add(name)
        claimed[name] = (anchor, int(n_str))

    # extra: in INDEX but not in SUMMARIES
    for name in claimed:
        if name not in actual:
            problems.append(
                f"PAPER_INDEX.md section list has '{name}' but no matching "
                "## header exists in PAPER_SUMMARIES.md"
            )

    # missing: in SUMMARIES but not in INDEX
    for name in sections:
        if name not in claimed:
            problems.append(
                f"PAPER_INDEX.md section list omits '{name}' — the section "
                "is present in PAPER_SUMMARIES.md but has no nested row"
            )

    # mismatched counts + stale anchors
    for name, actual_n in actual.items():
        if name not in claimed:
            continue
        anchor, claimed_n = claimed[name]
        if claimed_n != actual_n:
            problems.append(
                f"PAPER_INDEX.md section list claims '{name}' has "
                f"{claimed_n} papers, actual {actual_n}"
            )
        expected_anchor = _github_slug(name)
        if anchor != expected_anchor:
            problems.append(
                f"PAPER_INDEX.md section list row for '{name}' has anchor "
                f"'#{anchor}' but GitHub renders that section header as "
                f"'#{expected_anchor}' — link will 404"
            )

    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("root", nargs="?", default=".", help="repo root (default: cwd)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any problem is found (for CI / pre-commit)",
    )
    args = parser.parse_args(argv)

    try:
        report = audit_repo(args.root)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print("Counts:")
    for k, v in report.counts.items():
        print(f"  {k}: {v}")
    for name, items in report.problems.items():
        if items:
            print(f"\n{name} ({len(items)}):")
            for item in items:
                print(f"  - {item}")
    for name, items in report.info.items():
        if items:
            print(f"\n[info] {name} ({len(items)}, not failing):")
            for item in items:
                print(f"  - {item}")
    if report.ok:
        print("\nOK: docs and filesystem agree.")
    return 0 if report.ok or not args.check else 1


if __name__ == "__main__":
    sys.exit(main())
