"""Generate PAPER_INDEX.md's Quick Reference table and counts, plus PAPER_RELATED.md.

PAPER_SUMMARIES.md is the source of truth. Each ``###`` entry carries the
condense fields written by the ``condense-summary`` skill::

    - **Focus:** Compute governance, verification
    - **One-liner:** <=50-word thesis
    - **Related:** `slug-a`, `slug-b`
    - **Index label:** Shavit (OpenAI) (2023)   # only when the Title's
                                                # trailing parenthetical
                                                # does not parse

From those, this tool rewrites three marker-scoped blocks in PAPER_INDEX.md
(everything outside the markers is left byte-identical)::

    <!-- BEGIN GENERATED: counts -->          the "Summaries of N papers" line
    <!-- BEGIN GENERATED: quick-reference --> the | Slug | Paper | ... | table
    <!-- BEGIN GENERATED: section-list -->    the **papers/** bullet + rows

one in PAPER_SUMMARIES.md, when the repo carries the markers (a file without
them is never touched)::

    <!-- BEGIN GENERATED: summaries-header --> the "> N papers total" line

and writes PAPER_RELATED.md (wholly generated): per slug, which entries name
it in ``Related``.

Rules:
- Row order is section order, then entry order, as in PAPER_SUMMARIES.md.
- Key Contribution = One-liner. Paper = Index label, else derived from the
  Title parenthetical ``(<authors> — <org>, <year>)`` or ``(<authors>, <year>
  — <org>)`` -> ``<authors> (<org>) (<year>)``, ``(<authors>, <year>)`` ->
  ``<authors> (<year>)``, where ``<year>`` is a plain 4-digit year (optionally
  ``2024a`` or ``2024/2025``) and ``<org>`` is copied verbatim; anything else
  does not parse and is reported. File = first file (+N for multi-part), the
  text path for text-only entries, ``—`` for reference-only.
- Entries missing Focus or One-liner are reported and omitted (warning;
  error under ``--strict``). One-liners over 50 words warn, over 60 fail.
  A ``Related`` slug naming no entry is always an error.
- Counts come from ``count_papers.audit_repo`` — nothing is recounted here.

Usage (normally through ``paper_index.py index`` / ``check``):
    gen_index.py <root>            rewrite the generated blocks + PAPER_RELATED.md
    gen_index.py --check <root>    exit 1 with a unified diff if disk differs
    gen_index.py --strict ...      missing fields / unparseable labels fail
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from count_papers import (
    ConfigError,
    Entry,
    Report,
    _github_slug,
    audit_repo,
    section_counts,
)

ONE_LINER_WARN = 50
ONE_LINER_FAIL = 60

BEGIN_MARKER = "<!-- BEGIN GENERATED: {} -->"
END_MARKER = "<!-- END GENERATED: {} -->"

QR_HEADER = "| Slug | Paper | Focus | Key Contribution | File |"
QR_SEPARATOR = "|------|-------|-------|------------------|------|"

TITLE_PAREN_RE = re.compile(r"\(([^()]*)\)\s*$")
# Year slot: 2024, 2024a, 2024/2025, 2024–2025. Anything else there (a month,
# an arXiv version chain, a stray digit) fails closed, so the entry gets an
# explicit Index label rather than a silently mangled Paper cell. The org
# slot is used verbatim — "(…, 2025 — abridged version)" derives
# "… (abridged version) (2025)", which is on the Title, not the parser.
YEAR = r"\d{4}[a-z]?(?:\s*[/–-]\s*\d{4})?"
# (<authors> — <org>, <year>)
LABEL_ORG_FIRST_RE = re.compile(
    rf"^(?P<authors>.+?)\s+—\s+(?P<org>[^—]+?),\s*(?P<year>{YEAR})$"
)
# (<authors>, <year>[ — <org>])
LABEL_YEAR_FIRST_RE = re.compile(
    rf"^(?P<authors>.+?),\s*(?P<year>{YEAR})(?:\s+—\s+(?P<org>[^—]+))?$"
)

SUMMARIES_HEADER_BLOCK = "summaries-header"

RELATED_HEADER = """\
# Related entries

Generated by the paper-index skill (`paper_index.py index`) \
— do not edit by hand. Each row lists the entries whose bullet-form `- **Related:**` \
field (or one of its legacy names) names that slug: the reverse index of \
those fields only. Paragraph-form cross-reference blocks in older entries \
are not read until `condense-summary` converts them, so absence here is not \
evidence that nothing links to a slug. Forward links live in the entries.
"""


@dataclass
class Findings:
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    missing: list[str] = field(default_factory=list)  # one line per omitted entry
    omitted: list[Entry] = field(default_factory=list)


def word_count(text: str | None) -> int:
    """Same rule as condense_check.py: markup stripped, dashes and pipes ignored."""
    if not text:
        return 0
    cleaned = re.sub(r"[`*_]", " ", text)
    return len(re.findall(r"[^\s—–|]+", cleaned))


def derive_label(title: str) -> str | None:
    """Paper cell from the Title's trailing parenthetical, or None if it does not parse."""
    m = TITLE_PAREN_RE.search(title or "")
    if not m:
        return None
    inner = m.group(1).strip()
    parsed = LABEL_ORG_FIRST_RE.match(inner) or LABEL_YEAR_FIRST_RE.match(inner)
    if not parsed:
        return None
    authors = parsed.group("authors").strip()
    year = parsed.group("year").strip()
    org = (parsed.group("org") or "").strip()
    return f"{authors} ({org}) ({year})" if org else f"{authors} ({year})"


def paper_label(e: Entry) -> str | None:
    return e.index_label or derive_label(e.title)


def has_fields(e: Entry) -> bool:
    return e.focus is not None and e.one_liner is not None


def check_entries(entries: list[Entry], strict: bool = False) -> Findings:
    f = Findings()
    known = {e.slug for e in entries}
    soft = f.errors if strict else f.warnings
    for slug, n in Counter(e.slug for e in entries).items():
        if n > 1:
            f.errors.append(f"{slug}: `###` heading appears {n} times")
    for e in entries:
        for s in e.related:
            if s not in known:
                f.errors.append(f"{e.slug}: Related names no entry: `{s}`")
        missing = [
            name
            for name, val in (("Focus", e.focus), ("One-liner", e.one_liner))
            if val is None
        ]
        if missing:
            msg = (
                f"{e.slug}: missing {', '.join(missing)} — omitted from Quick Reference"
            )
            f.missing.append(msg)
            if strict:
                f.errors.append(msg)
            f.omitted.append(e)
            continue
        n = word_count(e.one_liner)
        if n > ONE_LINER_FAIL:
            f.errors.append(f"{e.slug}: One-liner is {n} words (> {ONE_LINER_FAIL})")
        elif n > ONE_LINER_WARN:
            f.warnings.append(f"{e.slug}: One-liner is {n} words (> {ONE_LINER_WARN})")
        if paper_label(e) is None:
            soft.append(
                f"{e.slug}: Title parenthetical does not parse and no Index label — Paper cell is '—'"
            )
    return f


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def file_cell(e: Entry) -> str:
    if e.category == "local_pdf" and e.pdf_refs:
        extra = f" (+{len(e.pdf_refs) - 1})" if len(e.pdf_refs) > 1 else ""
        return f"`{e.pdf_refs[0]}`{extra}"
    if e.category == "text_only" and e.text_refs:
        return f"`{e.text_refs[0]}`"
    return "—"


def quick_reference_entries(entries: list[Entry]) -> list[Entry]:
    return [e for e in entries if has_fields(e)]


def render_quick_reference(entries: list[Entry]) -> str:
    lines = [QR_HEADER, QR_SEPARATOR]
    for e in quick_reference_entries(entries):
        cells = [
            f"`{e.slug}`",
            paper_label(e) or "—",
            e.focus or "",
            e.one_liner or "",
            file_cell(e),
        ]
        lines.append("| " + " | ".join(_cell(c) for c in cells) + " |")
    return "\n".join(lines)


def render_counts(report: Report, n_rows: int) -> str:
    c = report.counts
    return (
        f"**PAPER_SUMMARIES.md** — Summaries of {c['entries']} papers across "
        f"{c['sections']} sections; {c['local_pdf']} papers have local PDFs, "
        f"{c['reference_only']} are reference-only, {c['text_only']} are text-only "
        "extractions of blog/web sources. The [Quick Reference](#quick-reference) "
        f"table below indexes {n_rows} of these by slug, author, or focus."
    )


def render_section_list(report: Report, n_rows: int) -> str:
    c = report.counts
    lines = [
        (
            f"**papers/** — {c['entries']} paper entries ({c['local_pdf']} local PDFs, "
            f"{c['reference_only']} reference-only, {c['text_only']} text-only web captures) "
            f"organized into {c['sections']} topical sections in PAPER_SUMMARIES.md. "
            f"The [Quick Reference](#quick-reference) table above indexes {n_rows} of these "
            "by slug/author/focus. Sections (with entry counts):"
        )
    ]
    for name, n in section_counts(report.entries, report.sections).items():
        lines.append(f"  - [{name}](PAPER_SUMMARIES.md#{_github_slug(name)}) ({n})")
    return "\n".join(lines)


def render_related(entries: list[Entry]) -> str:
    named_by: dict[str, list[str]] = {}
    for e in entries:
        for s in e.related:
            named_by.setdefault(s, []).append(e.slug)
    n_sources = sum(1 for e in entries if e.related)
    lines = [
        RELATED_HEADER,
        f"{n_sources} entries carry a `Related` field, naming {len(named_by)} distinct slugs.",
        "",
        "| Slug | Named as related by |",
        "|------|---------------------|",
    ]
    for slug in sorted(named_by):
        sources = ", ".join(f"`{s}`" for s in named_by[slug])
        lines.append(f"| `{slug}` | {sources} |")
    return "\n".join(lines) + "\n"


def has_block(text: str, name: str) -> bool:
    lines = text.split("\n")
    return BEGIN_MARKER.format(name) in lines and END_MARKER.format(name) in lines


def replace_block(
    text: str, name: str, body: str, filename: str = "PAPER_INDEX.md"
) -> str:
    begin, end = BEGIN_MARKER.format(name), END_MARKER.format(name)
    lines = text.split("\n")
    if begin not in lines or end not in lines:
        raise ValueError(
            f"{filename}: markers for block '{name}' not found ({begin} … {end})"
        )
    if lines.count(begin) != 1 or lines.count(end) != 1:
        raise ValueError(
            f"{filename}: markers for block '{name}' appear more than once — "
            "a duplicate pair would keep stale content forever"
        )
    i, j = lines.index(begin), lines.index(end)
    if j < i:
        raise ValueError(
            f"{filename}: END marker for block '{name}' precedes its BEGIN marker"
        )
    lines[i + 1 : j] = body.split("\n")
    return "\n".join(lines)


def render_summaries_header(report: Report) -> str:
    """The count line count_papers verifies: local + text-only, and the split."""
    c = report.counts
    return (
        f"> {c['local_pdf'] + c['text_only']} papers total "
        f"({c['local_pdf']} with local PDFs, {c['text_only']} text-only)."
    )


def render_summaries(summaries_text: str, report: Report) -> str:
    """PAPER_SUMMARIES.md with its header block rendered — or unchanged when
    the repo has no such markers (never invent them)."""
    if not has_block(summaries_text, SUMMARIES_HEADER_BLOCK):
        return summaries_text
    return replace_block(
        summaries_text,
        SUMMARIES_HEADER_BLOCK,
        render_summaries_header(report),
        filename="PAPER_SUMMARIES.md",
    )


def render_index(index_text: str, report: Report) -> str:
    n_rows = len(quick_reference_entries(report.entries))
    blocks = {
        "counts": render_counts(report, n_rows),
        "quick-reference": render_quick_reference(report.entries),
        "section-list": render_section_list(report, n_rows),
    }
    for name, body in blocks.items():
        index_text = replace_block(index_text, name, body)
    return index_text


def _diff(old: str, new: str, name: str) -> str:
    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"{name} (on disk)",
            tofile=f"{name} (generated)",
        )
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("root", nargs="?", default=".", help="repo root (default: cwd)")
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 with a diff if disk differs from the render",
    )
    ap.add_argument(
        "--strict",
        action="store_true",
        help="missing Focus/One-liner or unparseable label is an error",
    )
    ap.add_argument(
        "--verbose",
        action="store_true",
        help="list every entry omitted for missing fields (default: a count)",
    )
    args = ap.parse_args(argv)
    root = Path(args.root)

    try:
        report = audit_repo(root)
    except ConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    findings = check_entries(report.entries, strict=args.strict)
    for w in findings.warnings:
        print(f"warning: {w}", file=sys.stderr)
    for err in findings.errors:
        print(f"error: {err}", file=sys.stderr)
    if findings.missing and args.verbose and not args.strict:
        for m in findings.missing:
            print(f"omitted: {m}", file=sys.stderr)
    if findings.omitted:
        print(
            f"{len(findings.omitted)} of {len(report.entries)} entries omitted from the "
            "Quick Reference (missing Focus/One-liner; --verbose lists them)",
            file=sys.stderr,
        )
    if findings.errors:
        print(f"{len(findings.errors)} error(s); nothing written", file=sys.stderr)
        return 1

    index_path = root / "PAPER_INDEX.md"
    related_path = root / "PAPER_RELATED.md"
    summaries_path = root / "PAPER_SUMMARIES.md"
    try:
        old_index = index_path.read_text(encoding="utf-8")
        new_index = render_index(old_index, report)
        old_summaries = summaries_path.read_text(encoding="utf-8")
        new_summaries = render_summaries(old_summaries, report)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    new_related = render_related(report.entries)
    old_related = (
        related_path.read_text(encoding="utf-8") if related_path.is_file() else ""
    )

    if args.check:
        diffs = (
            _diff(old_summaries, new_summaries, "PAPER_SUMMARIES.md")
            + _diff(old_index, new_index, "PAPER_INDEX.md")
            + _diff(old_related, new_related, "PAPER_RELATED.md")
        )
        if diffs:
            sys.stdout.write(diffs)
            print(
                "generated index is stale — run `paper_index.py index .`",
                file=sys.stderr,
            )
            return 1
        print("OK: generated blocks and PAPER_RELATED.md are current.")
        return 0

    if new_summaries != old_summaries:
        summaries_path.write_text(new_summaries, encoding="utf-8")
    index_path.write_text(new_index, encoding="utf-8")
    related_path.write_text(new_related, encoding="utf-8")
    n_rows = len(quick_reference_entries(report.entries))
    print(f"wrote {index_path} ({n_rows} Quick Reference rows) and {related_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
